version: '3.8'

services:
  # PostgreSQL Database with TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: seatsync-postgres
    environment:
      POSTGRES_DB: seatsync
      POSTGRES_USER: seatsync_user
      POSTGRES_PASSWORD: seatsync_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - seatsync-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: seatsync-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - seatsync-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seatsync-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://seatsync_user:seatsync_password@postgres:5432/seatsync
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - seatsync-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seatsync-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - seatsync-network
    command: npm start

volumes:
  postgres_data:
  redis_data:

networks:
  seatsync-network:
    driver: bridge 